version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: calculator-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    image: ${DOCKERHUB_USERNAME}/calculator-backend:latest
    #build: ./calculator-backend
    container_name: calculator-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql
    networks:
      - calculator-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'echo > /dev/tcp/localhost/5000' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend:
    image: ${DOCKERHUB_USERNAME}/calculator-frontend:latest
    #build: ./calculator-frontend
    container_name: calculator-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - calculator-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  calculator-network:
    driver: bridge
