openapi: 3.0.4
info:
  title: Calculator API
  description: https://github.com/Prekols-Inc/calculator
  version: 0.1.9

servers:
  - url: http://localhost/v1

paths:
  /calculate:
    post:
      summary: Returns the result of calculation.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                expression:
                  type: string
              required:
                - expression
      responses:
        "200":
          description: A JSON with result
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                required:
                  - result
        "400":
          description: No expression in HTTP request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error

  /history:
    get:
      summary: Returns a list of calculations.
      responses:
        "200":
          description: A JSON array of calculations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    expression:
                      type: string
                    result:
                      type: string
                  required:
                    - expression
                    - result
